"""
Default configuration values for the Ethereum TxPool Fuzzer Core library.
These can be overridden by scenario-specific configurations.
"""

DEFAULT_TARGET_URL: str = "http://127.0.0.1:18546"
DEFAULT_CHAIN_ID: int = 20191003
DEFAULT_GAS_LIMIT: int = 21000

DEFAULT_TXPOOL_SIZE: int = 4
DEFAULT_FUTURE_SLOTS: int = 1

DEFAULT_KEY_FILE_PRIMARY: str = './key_prive2.csv'
DEFAULT_KEY_FILE_SECONDARY: str = './key_prive.csv'
DEFAULT_INITIAL_NONCE: int = 0
MAX_ACCOUNTS_TO_LOAD: int = 100

STATE_NORMAL_TX_PRICE_INDICATOR: int = 3
STATE_PARENT_REPLACEMENT_PRICE_THRESHOLD: int = 12000
STATE_CHILD_VALUE_THRESHOLD: int = 10000

DEFAULT_GRAPHVIZ_FILENAME: str = 'txpool_fuzz_graph'
DEFAULT_GRAPHVIZ_VIEW_ON_COMPLETE: bool = True

DEFAULT_MAX_FUZZ_ITERATIONS: int = 1000
DEFAULT_TIMEOUT_PER_ITERATION_SECONDS: float = 5.0
DEFAULT_GLOBAL_FUZZ_TIMEOUT_SECONDS: float = 3600.0

LOG_LEVEL: str = "INFO"
LOG_TO_FILE: bool = False
LOG_FILE_PATH: str = "fuzzer.log"
